### ISSUE TITLE
Will you keep on updating the protocol? 

### ISSUE THREAD

**Issue by ItsToxicGG** [ElyNetBE/ElyNetBE-PM3#1]
When March 1st will you still continue updating the protocol and stuff

**Comment by HanifWadowskyy** [comment]
Yes

**Comment by ItsToxicGG** [comment]
thats so great:D

**Comment by MCPE357** [comment]
> When March 1st will you still continue updating the protocol and stuff

use esko

**Comment by VaxPex** [comment]
https://github.com/Benedikt05/BetterAltay
https://github.com/MCPE357/EskoBE

**Comment by VaxPex** [comment]
https://discord.gg/bebavmUw

**Comment by VaxPex** [comment]
he will not he will only copy esko

**Comment by VaxPex** [comment]
use esko pm3 1.18.30

**Comment by krishna344d** [comment]
Yes make new one
