### ISSUE TITLE
for the dumbs

### ISSUE THREAD

**Issue by VaxPex** [ElyNetBE/ElyNetBE-PM3#20]
use eskobe or betteraltay cuz that dumb [HanifWadowskyy] is copying us and the name is copied 2

**Comment by VaxPex** [comment]
https://github.com/MCPE357/EskoBE

**Comment by VaxPex** [comment]
https://github.com/Benedikt05/BetterAltay

**Comment by VaxPex** [comment]
😂

**Comment by VaxPex** [comment]
close it but u wont admit

**Comment by HanifWadowskyy** [comment]
Noisy you're ugly

**Comment by VaxPex** [comment]
so are u?

**Comment by MCPE357** [comment]
> Noisy you're ugly

get a life

**Comment by andriycraft** [comment]
what is happening?
